{

//ISSO É BLOCOS DE CÓDIGO, QUE FICAM DENTRO DE CHAVEZ.

// SERVE PARA COLOCAR ALGUNS CÓDIGOS GRANDES E CASO QUEIRA SEPARAR ESSE CÓDIGO DOS DEMAIS

}


{ console.log("ISSO E UM COIDIGO DENTRO DE UM BLOCO!!!");

    {

                //PODEMOS TER VARIOS BLOCOS, INCLUSIVE UM DENTRO DO OUTRO

        
        { //ASSIM COMO FIZ ESSE DE EXEMPLO E ELES FICAM SEPARADOS
        
        

        }


    }


}