console.log('passo 1'); 
console.log('passo 2'); // EXEMPLO DE CONSOLE.LOG
console.log('passo 3');

// BARRA BARRA É USADO COMO COMENTÁRIO SIMPLES EM UMA ÚNICA LINHA

/* BARRA COM ASTERISCO É USADO PARA TIPO DE COMENTÁRIOS MAIORES QUE PRECISAM DE 
MAIS DE UMA LINHA 
OU CASO DESEJAMOS PULAR UMA LINHA PARA ORGANIZAR O COMENTÁRIO DE FORMA DIFERENTE */

/* TAMBÉM POSSO PULAR LINHAS E COLOCAR ASTERISCO A CADA LINHA QUE EU PULAR, POR EXEMPLO
 *
 * COLOCANDO ASTERISCO EM CADA LINHA, É SÓ PULAR A LINHA QUE AUTOMATICAMENTE O 
 * ASTERISCO É COLOCADO
 * 
 * PORÉM PARA ATIVAR ESSA FUNÇÃO,
 * 
 * VC PRECISA COLOCAR O (*BARRA ASTERISCO NO INICIO E NO FIM COLOCAR INVERSO, 
 * 
 * OU SEJA, COLOCAR ASTERISCO E BARRA PARA FECHAR O COMENTÁRIO
 * 
 * E APÓS ISSO
 * COLOCAR (ASTERISCO NAS DUAS PRIMEIRAS LINHAS ACRESCIDO DE UM ESPAÇO ANTES 
 * E APÓS ISSO O PROGRAMA ENTEDE QUE VOCE QUER QUE ELE ACRESCENTE ASTERISCO
 * NAS DEMAIS LINHAS))
 * 
 *
 */
